services:
  web:
    # image: php:8.2-apache
    build: .
    ports:
      - "8080:80"
    volumes:
      # This is the link between your home dir and the server
      - ./www:/var/www/html
    restart: always

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kdnd
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      # This tells phpMyAdmin which database service to connect to
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    restart: always
volumes:
  db_data:
